/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Nov  9 05:43:47 UTC 2018
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkMergeSort_h__
#define __mkMergeSort_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkMergeSort module */
class MOD_mkMergeSort : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_finishFlag;
  MOD_Reg<tUInt8> INST_flag1;
  MOD_Reg<tUInt8> INST_flag10;
  MOD_Reg<tUInt8> INST_flag11;
  MOD_Reg<tUInt8> INST_flag12;
  MOD_Reg<tUInt8> INST_flag13;
  MOD_Reg<tUInt8> INST_flag14;
  MOD_Reg<tUInt8> INST_flag15;
  MOD_Reg<tUInt8> INST_flag16;
  MOD_Reg<tUInt8> INST_flag2;
  MOD_Reg<tUInt8> INST_flag3;
  MOD_Reg<tUInt8> INST_flag4;
  MOD_Reg<tUInt8> INST_flag5;
  MOD_Reg<tUInt8> INST_flag6;
  MOD_Reg<tUInt8> INST_flag7;
  MOD_Reg<tUInt8> INST_flag8;
  MOD_Reg<tUInt8> INST_flag9;
  MOD_Reg<tUInt8> INST_storage_0_0;
  MOD_Reg<tUInt8> INST_storage_0_1;
  MOD_Reg<tUInt8> INST_storage_0_10;
  MOD_Reg<tUInt8> INST_storage_0_11;
  MOD_Reg<tUInt8> INST_storage_0_12;
  MOD_Reg<tUInt8> INST_storage_0_13;
  MOD_Reg<tUInt8> INST_storage_0_14;
  MOD_Reg<tUInt8> INST_storage_0_15;
  MOD_Reg<tUInt8> INST_storage_0_2;
  MOD_Reg<tUInt8> INST_storage_0_3;
  MOD_Reg<tUInt8> INST_storage_0_4;
  MOD_Reg<tUInt8> INST_storage_0_5;
  MOD_Reg<tUInt8> INST_storage_0_6;
  MOD_Reg<tUInt8> INST_storage_0_7;
  MOD_Reg<tUInt8> INST_storage_0_8;
  MOD_Reg<tUInt8> INST_storage_0_9;
  MOD_Reg<tUInt8> INST_storage_10_0;
  MOD_Reg<tUInt8> INST_storage_10_1;
  MOD_Reg<tUInt8> INST_storage_10_10;
  MOD_Reg<tUInt8> INST_storage_10_11;
  MOD_Reg<tUInt8> INST_storage_10_12;
  MOD_Reg<tUInt8> INST_storage_10_13;
  MOD_Reg<tUInt8> INST_storage_10_14;
  MOD_Reg<tUInt8> INST_storage_10_15;
  MOD_Reg<tUInt8> INST_storage_10_2;
  MOD_Reg<tUInt8> INST_storage_10_3;
  MOD_Reg<tUInt8> INST_storage_10_4;
  MOD_Reg<tUInt8> INST_storage_10_5;
  MOD_Reg<tUInt8> INST_storage_10_6;
  MOD_Reg<tUInt8> INST_storage_10_7;
  MOD_Reg<tUInt8> INST_storage_10_8;
  MOD_Reg<tUInt8> INST_storage_10_9;
  MOD_Reg<tUInt8> INST_storage_11_0;
  MOD_Reg<tUInt8> INST_storage_11_1;
  MOD_Reg<tUInt8> INST_storage_11_10;
  MOD_Reg<tUInt8> INST_storage_11_11;
  MOD_Reg<tUInt8> INST_storage_11_12;
  MOD_Reg<tUInt8> INST_storage_11_13;
  MOD_Reg<tUInt8> INST_storage_11_14;
  MOD_Reg<tUInt8> INST_storage_11_15;
  MOD_Reg<tUInt8> INST_storage_11_2;
  MOD_Reg<tUInt8> INST_storage_11_3;
  MOD_Reg<tUInt8> INST_storage_11_4;
  MOD_Reg<tUInt8> INST_storage_11_5;
  MOD_Reg<tUInt8> INST_storage_11_6;
  MOD_Reg<tUInt8> INST_storage_11_7;
  MOD_Reg<tUInt8> INST_storage_11_8;
  MOD_Reg<tUInt8> INST_storage_11_9;
  MOD_Reg<tUInt8> INST_storage_12_0;
  MOD_Reg<tUInt8> INST_storage_12_1;
  MOD_Reg<tUInt8> INST_storage_12_10;
  MOD_Reg<tUInt8> INST_storage_12_11;
  MOD_Reg<tUInt8> INST_storage_12_12;
  MOD_Reg<tUInt8> INST_storage_12_13;
  MOD_Reg<tUInt8> INST_storage_12_14;
  MOD_Reg<tUInt8> INST_storage_12_15;
  MOD_Reg<tUInt8> INST_storage_12_2;
  MOD_Reg<tUInt8> INST_storage_12_3;
  MOD_Reg<tUInt8> INST_storage_12_4;
  MOD_Reg<tUInt8> INST_storage_12_5;
  MOD_Reg<tUInt8> INST_storage_12_6;
  MOD_Reg<tUInt8> INST_storage_12_7;
  MOD_Reg<tUInt8> INST_storage_12_8;
  MOD_Reg<tUInt8> INST_storage_12_9;
  MOD_Reg<tUInt8> INST_storage_13_0;
  MOD_Reg<tUInt8> INST_storage_13_1;
  MOD_Reg<tUInt8> INST_storage_13_10;
  MOD_Reg<tUInt8> INST_storage_13_11;
  MOD_Reg<tUInt8> INST_storage_13_12;
  MOD_Reg<tUInt8> INST_storage_13_13;
  MOD_Reg<tUInt8> INST_storage_13_14;
  MOD_Reg<tUInt8> INST_storage_13_15;
  MOD_Reg<tUInt8> INST_storage_13_2;
  MOD_Reg<tUInt8> INST_storage_13_3;
  MOD_Reg<tUInt8> INST_storage_13_4;
  MOD_Reg<tUInt8> INST_storage_13_5;
  MOD_Reg<tUInt8> INST_storage_13_6;
  MOD_Reg<tUInt8> INST_storage_13_7;
  MOD_Reg<tUInt8> INST_storage_13_8;
  MOD_Reg<tUInt8> INST_storage_13_9;
  MOD_Reg<tUInt8> INST_storage_14_0;
  MOD_Reg<tUInt8> INST_storage_14_1;
  MOD_Reg<tUInt8> INST_storage_14_10;
  MOD_Reg<tUInt8> INST_storage_14_11;
  MOD_Reg<tUInt8> INST_storage_14_12;
  MOD_Reg<tUInt8> INST_storage_14_13;
  MOD_Reg<tUInt8> INST_storage_14_14;
  MOD_Reg<tUInt8> INST_storage_14_15;
  MOD_Reg<tUInt8> INST_storage_14_2;
  MOD_Reg<tUInt8> INST_storage_14_3;
  MOD_Reg<tUInt8> INST_storage_14_4;
  MOD_Reg<tUInt8> INST_storage_14_5;
  MOD_Reg<tUInt8> INST_storage_14_6;
  MOD_Reg<tUInt8> INST_storage_14_7;
  MOD_Reg<tUInt8> INST_storage_14_8;
  MOD_Reg<tUInt8> INST_storage_14_9;
  MOD_Reg<tUInt8> INST_storage_15_0;
  MOD_Reg<tUInt8> INST_storage_15_1;
  MOD_Reg<tUInt8> INST_storage_15_10;
  MOD_Reg<tUInt8> INST_storage_15_11;
  MOD_Reg<tUInt8> INST_storage_15_12;
  MOD_Reg<tUInt8> INST_storage_15_13;
  MOD_Reg<tUInt8> INST_storage_15_14;
  MOD_Reg<tUInt8> INST_storage_15_15;
  MOD_Reg<tUInt8> INST_storage_15_2;
  MOD_Reg<tUInt8> INST_storage_15_3;
  MOD_Reg<tUInt8> INST_storage_15_4;
  MOD_Reg<tUInt8> INST_storage_15_5;
  MOD_Reg<tUInt8> INST_storage_15_6;
  MOD_Reg<tUInt8> INST_storage_15_7;
  MOD_Reg<tUInt8> INST_storage_15_8;
  MOD_Reg<tUInt8> INST_storage_15_9;
  MOD_Reg<tUInt8> INST_storage_16_0;
  MOD_Reg<tUInt8> INST_storage_16_1;
  MOD_Reg<tUInt8> INST_storage_16_10;
  MOD_Reg<tUInt8> INST_storage_16_11;
  MOD_Reg<tUInt8> INST_storage_16_12;
  MOD_Reg<tUInt8> INST_storage_16_13;
  MOD_Reg<tUInt8> INST_storage_16_14;
  MOD_Reg<tUInt8> INST_storage_16_15;
  MOD_Reg<tUInt8> INST_storage_16_2;
  MOD_Reg<tUInt8> INST_storage_16_3;
  MOD_Reg<tUInt8> INST_storage_16_4;
  MOD_Reg<tUInt8> INST_storage_16_5;
  MOD_Reg<tUInt8> INST_storage_16_6;
  MOD_Reg<tUInt8> INST_storage_16_7;
  MOD_Reg<tUInt8> INST_storage_16_8;
  MOD_Reg<tUInt8> INST_storage_16_9;
  MOD_Reg<tUInt8> INST_storage_1_0;
  MOD_Reg<tUInt8> INST_storage_1_1;
  MOD_Reg<tUInt8> INST_storage_1_10;
  MOD_Reg<tUInt8> INST_storage_1_11;
  MOD_Reg<tUInt8> INST_storage_1_12;
  MOD_Reg<tUInt8> INST_storage_1_13;
  MOD_Reg<tUInt8> INST_storage_1_14;
  MOD_Reg<tUInt8> INST_storage_1_15;
  MOD_Reg<tUInt8> INST_storage_1_2;
  MOD_Reg<tUInt8> INST_storage_1_3;
  MOD_Reg<tUInt8> INST_storage_1_4;
  MOD_Reg<tUInt8> INST_storage_1_5;
  MOD_Reg<tUInt8> INST_storage_1_6;
  MOD_Reg<tUInt8> INST_storage_1_7;
  MOD_Reg<tUInt8> INST_storage_1_8;
  MOD_Reg<tUInt8> INST_storage_1_9;
  MOD_Reg<tUInt8> INST_storage_2_0;
  MOD_Reg<tUInt8> INST_storage_2_1;
  MOD_Reg<tUInt8> INST_storage_2_10;
  MOD_Reg<tUInt8> INST_storage_2_11;
  MOD_Reg<tUInt8> INST_storage_2_12;
  MOD_Reg<tUInt8> INST_storage_2_13;
  MOD_Reg<tUInt8> INST_storage_2_14;
  MOD_Reg<tUInt8> INST_storage_2_15;
  MOD_Reg<tUInt8> INST_storage_2_2;
  MOD_Reg<tUInt8> INST_storage_2_3;
  MOD_Reg<tUInt8> INST_storage_2_4;
  MOD_Reg<tUInt8> INST_storage_2_5;
  MOD_Reg<tUInt8> INST_storage_2_6;
  MOD_Reg<tUInt8> INST_storage_2_7;
  MOD_Reg<tUInt8> INST_storage_2_8;
  MOD_Reg<tUInt8> INST_storage_2_9;
  MOD_Reg<tUInt8> INST_storage_3_0;
  MOD_Reg<tUInt8> INST_storage_3_1;
  MOD_Reg<tUInt8> INST_storage_3_10;
  MOD_Reg<tUInt8> INST_storage_3_11;
  MOD_Reg<tUInt8> INST_storage_3_12;
  MOD_Reg<tUInt8> INST_storage_3_13;
  MOD_Reg<tUInt8> INST_storage_3_14;
  MOD_Reg<tUInt8> INST_storage_3_15;
  MOD_Reg<tUInt8> INST_storage_3_2;
  MOD_Reg<tUInt8> INST_storage_3_3;
  MOD_Reg<tUInt8> INST_storage_3_4;
  MOD_Reg<tUInt8> INST_storage_3_5;
  MOD_Reg<tUInt8> INST_storage_3_6;
  MOD_Reg<tUInt8> INST_storage_3_7;
  MOD_Reg<tUInt8> INST_storage_3_8;
  MOD_Reg<tUInt8> INST_storage_3_9;
  MOD_Reg<tUInt8> INST_storage_4_0;
  MOD_Reg<tUInt8> INST_storage_4_1;
  MOD_Reg<tUInt8> INST_storage_4_10;
  MOD_Reg<tUInt8> INST_storage_4_11;
  MOD_Reg<tUInt8> INST_storage_4_12;
  MOD_Reg<tUInt8> INST_storage_4_13;
  MOD_Reg<tUInt8> INST_storage_4_14;
  MOD_Reg<tUInt8> INST_storage_4_15;
  MOD_Reg<tUInt8> INST_storage_4_2;
  MOD_Reg<tUInt8> INST_storage_4_3;
  MOD_Reg<tUInt8> INST_storage_4_4;
  MOD_Reg<tUInt8> INST_storage_4_5;
  MOD_Reg<tUInt8> INST_storage_4_6;
  MOD_Reg<tUInt8> INST_storage_4_7;
  MOD_Reg<tUInt8> INST_storage_4_8;
  MOD_Reg<tUInt8> INST_storage_4_9;
  MOD_Reg<tUInt8> INST_storage_5_0;
  MOD_Reg<tUInt8> INST_storage_5_1;
  MOD_Reg<tUInt8> INST_storage_5_10;
  MOD_Reg<tUInt8> INST_storage_5_11;
  MOD_Reg<tUInt8> INST_storage_5_12;
  MOD_Reg<tUInt8> INST_storage_5_13;
  MOD_Reg<tUInt8> INST_storage_5_14;
  MOD_Reg<tUInt8> INST_storage_5_15;
  MOD_Reg<tUInt8> INST_storage_5_2;
  MOD_Reg<tUInt8> INST_storage_5_3;
  MOD_Reg<tUInt8> INST_storage_5_4;
  MOD_Reg<tUInt8> INST_storage_5_5;
  MOD_Reg<tUInt8> INST_storage_5_6;
  MOD_Reg<tUInt8> INST_storage_5_7;
  MOD_Reg<tUInt8> INST_storage_5_8;
  MOD_Reg<tUInt8> INST_storage_5_9;
  MOD_Reg<tUInt8> INST_storage_6_0;
  MOD_Reg<tUInt8> INST_storage_6_1;
  MOD_Reg<tUInt8> INST_storage_6_10;
  MOD_Reg<tUInt8> INST_storage_6_11;
  MOD_Reg<tUInt8> INST_storage_6_12;
  MOD_Reg<tUInt8> INST_storage_6_13;
  MOD_Reg<tUInt8> INST_storage_6_14;
  MOD_Reg<tUInt8> INST_storage_6_15;
  MOD_Reg<tUInt8> INST_storage_6_2;
  MOD_Reg<tUInt8> INST_storage_6_3;
  MOD_Reg<tUInt8> INST_storage_6_4;
  MOD_Reg<tUInt8> INST_storage_6_5;
  MOD_Reg<tUInt8> INST_storage_6_6;
  MOD_Reg<tUInt8> INST_storage_6_7;
  MOD_Reg<tUInt8> INST_storage_6_8;
  MOD_Reg<tUInt8> INST_storage_6_9;
  MOD_Reg<tUInt8> INST_storage_7_0;
  MOD_Reg<tUInt8> INST_storage_7_1;
  MOD_Reg<tUInt8> INST_storage_7_10;
  MOD_Reg<tUInt8> INST_storage_7_11;
  MOD_Reg<tUInt8> INST_storage_7_12;
  MOD_Reg<tUInt8> INST_storage_7_13;
  MOD_Reg<tUInt8> INST_storage_7_14;
  MOD_Reg<tUInt8> INST_storage_7_15;
  MOD_Reg<tUInt8> INST_storage_7_2;
  MOD_Reg<tUInt8> INST_storage_7_3;
  MOD_Reg<tUInt8> INST_storage_7_4;
  MOD_Reg<tUInt8> INST_storage_7_5;
  MOD_Reg<tUInt8> INST_storage_7_6;
  MOD_Reg<tUInt8> INST_storage_7_7;
  MOD_Reg<tUInt8> INST_storage_7_8;
  MOD_Reg<tUInt8> INST_storage_7_9;
  MOD_Reg<tUInt8> INST_storage_8_0;
  MOD_Reg<tUInt8> INST_storage_8_1;
  MOD_Reg<tUInt8> INST_storage_8_10;
  MOD_Reg<tUInt8> INST_storage_8_11;
  MOD_Reg<tUInt8> INST_storage_8_12;
  MOD_Reg<tUInt8> INST_storage_8_13;
  MOD_Reg<tUInt8> INST_storage_8_14;
  MOD_Reg<tUInt8> INST_storage_8_15;
  MOD_Reg<tUInt8> INST_storage_8_2;
  MOD_Reg<tUInt8> INST_storage_8_3;
  MOD_Reg<tUInt8> INST_storage_8_4;
  MOD_Reg<tUInt8> INST_storage_8_5;
  MOD_Reg<tUInt8> INST_storage_8_6;
  MOD_Reg<tUInt8> INST_storage_8_7;
  MOD_Reg<tUInt8> INST_storage_8_8;
  MOD_Reg<tUInt8> INST_storage_8_9;
  MOD_Reg<tUInt8> INST_storage_9_0;
  MOD_Reg<tUInt8> INST_storage_9_1;
  MOD_Reg<tUInt8> INST_storage_9_10;
  MOD_Reg<tUInt8> INST_storage_9_11;
  MOD_Reg<tUInt8> INST_storage_9_12;
  MOD_Reg<tUInt8> INST_storage_9_13;
  MOD_Reg<tUInt8> INST_storage_9_14;
  MOD_Reg<tUInt8> INST_storage_9_15;
  MOD_Reg<tUInt8> INST_storage_9_2;
  MOD_Reg<tUInt8> INST_storage_9_3;
  MOD_Reg<tUInt8> INST_storage_9_4;
  MOD_Reg<tUInt8> INST_storage_9_5;
  MOD_Reg<tUInt8> INST_storage_9_6;
  MOD_Reg<tUInt8> INST_storage_9_7;
  MOD_Reg<tUInt8> INST_storage_9_8;
  MOD_Reg<tUInt8> INST_storage_9_9;
 
 /* Constructor */
 public:
  MOD_mkMergeSort(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_rulefinish;
  tUInt8 DEF_CAN_FIRE_RL_rulefinish;
  tUInt8 DEF_WILL_FIRE_RL_rule15;
  tUInt8 DEF_CAN_FIRE_RL_rule15;
  tUInt8 DEF_WILL_FIRE_RL_rule14;
  tUInt8 DEF_CAN_FIRE_RL_rule14;
  tUInt8 DEF_WILL_FIRE_RL_rule9;
  tUInt8 DEF_CAN_FIRE_RL_rule9;
  tUInt8 DEF_WILL_FIRE_RL_rule8;
  tUInt8 DEF_CAN_FIRE_RL_rule8;
  tUInt8 DEF_WILL_FIRE_RL_rule4;
  tUInt8 DEF_CAN_FIRE_RL_rule4;
  tUInt8 DEF_WILL_FIRE_RL_rule16;
  tUInt8 DEF_CAN_FIRE_RL_rule16;
  tUInt8 DEF_WILL_FIRE_RL_rule12;
  tUInt8 DEF_CAN_FIRE_RL_rule12;
  tUInt8 DEF_WILL_FIRE_RL_rule11;
  tUInt8 DEF_CAN_FIRE_RL_rule11;
  tUInt8 DEF_WILL_FIRE_RL_rule10;
  tUInt8 DEF_CAN_FIRE_RL_rule10;
  tUInt8 DEF_WILL_FIRE_RL_rule6;
  tUInt8 DEF_CAN_FIRE_RL_rule6;
  tUInt8 DEF_WILL_FIRE_RL_rule5;
  tUInt8 DEF_CAN_FIRE_RL_rule5;
  tUInt8 DEF_WILL_FIRE_RL_rule2;
  tUInt8 DEF_CAN_FIRE_RL_rule2;
  tUInt8 DEF_WILL_FIRE_RL_rule13;
  tUInt8 DEF_CAN_FIRE_RL_rule13;
  tUInt8 DEF_WILL_FIRE_RL_rule7;
  tUInt8 DEF_CAN_FIRE_RL_rule7;
  tUInt8 DEF_WILL_FIRE_RL_rule3;
  tUInt8 DEF_CAN_FIRE_RL_rule3;
  tUInt8 DEF_WILL_FIRE_RL_rule1;
  tUInt8 DEF_CAN_FIRE_RL_rule1;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h21539;
  tUInt8 DEF_x__h21588;
  tUInt8 DEF_x__h21217;
  tUInt8 DEF_x__h21266;
  tUInt8 DEF_x__h20895;
  tUInt8 DEF_x__h20944;
  tUInt8 DEF_x__h20573;
  tUInt8 DEF_x__h20622;
  tUInt8 DEF_x__h20251;
  tUInt8 DEF_x__h20300;
  tUInt8 DEF_x__h19929;
  tUInt8 DEF_x__h19978;
  tUInt8 DEF_x__h19607;
  tUInt8 DEF_x__h19656;
  tUInt8 DEF_x__h19285;
  tUInt8 DEF_x__h19334;
 
 /* Rules */
 public:
  void RL_rule1();
  void RL_rule3();
  void RL_rule7();
  void RL_rule13();
  void RL_rule2();
  void RL_rule5();
  void RL_rule6();
  void RL_rule10();
  void RL_rule11();
  void RL_rule12();
  void RL_rule16();
  void RL_rule4();
  void RL_rule8();
  void RL_rule9();
  void RL_rule14();
  void RL_rule15();
  void RL_rulefinish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMergeSort &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMergeSort &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMergeSort &backing);
};

#endif /* ifndef __mkMergeSort_h__ */
