/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Nov  9 05:43:47 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkMergeSort.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkMergeSort::MODEL_mkMergeSort()
{
  mkMergeSort_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkMergeSort()
{
  MODEL_mkMergeSort *model = new MODEL_mkMergeSort();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkMergeSort &INST_top = *((MOD_mkMergeSort *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_flag1__h17944;
	 tUInt8 DEF_INST_top_DEF_flag2__h21689;
	 tUInt8 DEF_INST_top_DEF_flag3__h21686;
	 tUInt8 DEF_INST_top_DEF_flag4__h33162;
	 tUInt8 DEF_INST_top_DEF_flag5__h33159;
	 tUInt8 DEF_INST_top_DEF_flag6__h25251;
	 tUInt8 DEF_INST_top_DEF_flag7__h25248;
	 tUInt8 DEF_INST_top_DEF_flag8__h44103;
	 tUInt8 DEF_INST_top_DEF_flag9__h35696;
	 tUInt8 DEF_INST_top_DEF_flag10__h35693;
	 tUInt8 DEF_INST_top_DEF_flag11__h37442;
	 tUInt8 DEF_INST_top_DEF_flag12__h28813;
	 tUInt8 DEF_INST_top_DEF_flag13__h28810;
	 tUInt8 DEF_INST_top_DEF_flag14__h48035;
	 tUInt8 DEF_INST_top_DEF_flag15__h39497;
	 tUInt8 DEF_INST_top_DEF_flag16__h39494;
	 tUInt8 DEF_INST_top_DEF_finishFlag__h51965;
	 DEF_INST_top_DEF_flag1__h17944 = INST_top.INST_flag1.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule1 = !DEF_INST_top_DEF_flag1__h17944;
	 INST_top.DEF_WILL_FIRE_RL_rule1 = INST_top.DEF_CAN_FIRE_RL_rule1;
	 DEF_INST_top_DEF_flag10__h35693 = INST_top.INST_flag10.METH_read();
	 DEF_INST_top_DEF_flag9__h35696 = INST_top.INST_flag9.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule10 = !DEF_INST_top_DEF_flag10__h35693 && DEF_INST_top_DEF_flag9__h35696;
	 INST_top.DEF_WILL_FIRE_RL_rule10 = INST_top.DEF_CAN_FIRE_RL_rule10;
	 DEF_INST_top_DEF_flag11__h37442 = INST_top.INST_flag11.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule11 = !DEF_INST_top_DEF_flag11__h37442 && DEF_INST_top_DEF_flag10__h35693;
	 INST_top.DEF_WILL_FIRE_RL_rule11 = INST_top.DEF_CAN_FIRE_RL_rule11;
	 DEF_INST_top_DEF_flag12__h28813 = INST_top.INST_flag12.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule12 = !DEF_INST_top_DEF_flag12__h28813 && DEF_INST_top_DEF_flag11__h37442;
	 INST_top.DEF_WILL_FIRE_RL_rule12 = INST_top.DEF_CAN_FIRE_RL_rule12;
	 DEF_INST_top_DEF_flag13__h28810 = INST_top.INST_flag13.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule13 = !DEF_INST_top_DEF_flag13__h28810 && DEF_INST_top_DEF_flag12__h28813;
	 INST_top.DEF_WILL_FIRE_RL_rule13 = INST_top.DEF_CAN_FIRE_RL_rule13;
	 DEF_INST_top_DEF_flag14__h48035 = INST_top.INST_flag14.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule14 = !DEF_INST_top_DEF_flag14__h48035 && DEF_INST_top_DEF_flag13__h28810;
	 INST_top.DEF_WILL_FIRE_RL_rule14 = INST_top.DEF_CAN_FIRE_RL_rule14;
	 DEF_INST_top_DEF_flag15__h39497 = INST_top.INST_flag15.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule15 = !DEF_INST_top_DEF_flag15__h39497 && DEF_INST_top_DEF_flag14__h48035;
	 INST_top.DEF_WILL_FIRE_RL_rule15 = INST_top.DEF_CAN_FIRE_RL_rule15;
	 DEF_INST_top_DEF_flag16__h39494 = INST_top.INST_flag16.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule16 = !DEF_INST_top_DEF_flag16__h39494 && DEF_INST_top_DEF_flag15__h39497;
	 INST_top.DEF_WILL_FIRE_RL_rule16 = INST_top.DEF_CAN_FIRE_RL_rule16;
	 DEF_INST_top_DEF_flag2__h21689 = INST_top.INST_flag2.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule2 = !DEF_INST_top_DEF_flag2__h21689 && DEF_INST_top_DEF_flag1__h17944;
	 INST_top.DEF_WILL_FIRE_RL_rule2 = INST_top.DEF_CAN_FIRE_RL_rule2;
	 DEF_INST_top_DEF_flag3__h21686 = INST_top.INST_flag3.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule3 = !DEF_INST_top_DEF_flag3__h21686 && DEF_INST_top_DEF_flag2__h21689;
	 INST_top.DEF_WILL_FIRE_RL_rule3 = INST_top.DEF_CAN_FIRE_RL_rule3;
	 DEF_INST_top_DEF_flag4__h33162 = INST_top.INST_flag4.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule4 = !DEF_INST_top_DEF_flag4__h33162 && DEF_INST_top_DEF_flag3__h21686;
	 INST_top.DEF_WILL_FIRE_RL_rule4 = INST_top.DEF_CAN_FIRE_RL_rule4;
	 DEF_INST_top_DEF_flag5__h33159 = INST_top.INST_flag5.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule5 = !DEF_INST_top_DEF_flag5__h33159 && DEF_INST_top_DEF_flag4__h33162;
	 INST_top.DEF_WILL_FIRE_RL_rule5 = INST_top.DEF_CAN_FIRE_RL_rule5;
	 DEF_INST_top_DEF_flag6__h25251 = INST_top.INST_flag6.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule6 = !DEF_INST_top_DEF_flag6__h25251 && DEF_INST_top_DEF_flag5__h33159;
	 INST_top.DEF_WILL_FIRE_RL_rule6 = INST_top.DEF_CAN_FIRE_RL_rule6;
	 DEF_INST_top_DEF_flag7__h25248 = INST_top.INST_flag7.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule7 = !DEF_INST_top_DEF_flag7__h25248 && DEF_INST_top_DEF_flag6__h25251;
	 INST_top.DEF_WILL_FIRE_RL_rule7 = INST_top.DEF_CAN_FIRE_RL_rule7;
	 DEF_INST_top_DEF_flag8__h44103 = INST_top.INST_flag8.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rule8 = !DEF_INST_top_DEF_flag8__h44103 && DEF_INST_top_DEF_flag7__h25248;
	 INST_top.DEF_WILL_FIRE_RL_rule8 = INST_top.DEF_CAN_FIRE_RL_rule8;
	 INST_top.DEF_CAN_FIRE_RL_rule9 = !DEF_INST_top_DEF_flag9__h35696 && DEF_INST_top_DEF_flag8__h44103;
	 INST_top.DEF_WILL_FIRE_RL_rule9 = INST_top.DEF_CAN_FIRE_RL_rule9;
	 DEF_INST_top_DEF_finishFlag__h51965 = INST_top.INST_finishFlag.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_rulefinish = DEF_INST_top_DEF_flag16__h39494 && !DEF_INST_top_DEF_finishFlag__h51965;
	 INST_top.DEF_WILL_FIRE_RL_rulefinish = INST_top.DEF_CAN_FIRE_RL_rulefinish;
	 if (INST_top.DEF_WILL_FIRE_RL_rule1)
	   INST_top.RL_rule1();
	 if (INST_top.DEF_WILL_FIRE_RL_rule10)
	   INST_top.RL_rule10();
	 if (INST_top.DEF_WILL_FIRE_RL_rule11)
	   INST_top.RL_rule11();
	 if (INST_top.DEF_WILL_FIRE_RL_rule12)
	   INST_top.RL_rule12();
	 if (INST_top.DEF_WILL_FIRE_RL_rule13)
	   INST_top.RL_rule13();
	 if (INST_top.DEF_WILL_FIRE_RL_rule14)
	   INST_top.RL_rule14();
	 if (INST_top.DEF_WILL_FIRE_RL_rule16)
	   INST_top.RL_rule16();
	 if (INST_top.DEF_WILL_FIRE_RL_rule15)
	   INST_top.RL_rule15();
	 if (INST_top.DEF_WILL_FIRE_RL_rule2)
	   INST_top.RL_rule2();
	 if (INST_top.DEF_WILL_FIRE_RL_rule3)
	   INST_top.RL_rule3();
	 if (INST_top.DEF_WILL_FIRE_RL_rule4)
	   INST_top.RL_rule4();
	 if (INST_top.DEF_WILL_FIRE_RL_rule5)
	   INST_top.RL_rule5();
	 if (INST_top.DEF_WILL_FIRE_RL_rule6)
	   INST_top.RL_rule6();
	 if (INST_top.DEF_WILL_FIRE_RL_rule7)
	   INST_top.RL_rule7();
	 if (INST_top.DEF_WILL_FIRE_RL_rule8)
	   INST_top.RL_rule8();
	 if (INST_top.DEF_WILL_FIRE_RL_rule9)
	   INST_top.RL_rule9();
	 if (INST_top.DEF_WILL_FIRE_RL_rulefinish)
	   INST_top.RL_rulefinish();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_flag1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_flag16.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_finishFlag.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_0_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_1_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_2_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_3_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_4_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_5_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_6_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_7_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_8_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_9_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_10_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_11_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_12_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_13_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_14_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_15_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_storage_16_15.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkMergeSort::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkMergeSort_instance = new MOD_mkMergeSort(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkMergeSort_instance->set_clk_0)("CLK");
}
void MODEL_mkMergeSort::destroy_model()
{
  delete mkMergeSort_instance;
  mkMergeSort_instance = NULL;
}
void MODEL_mkMergeSort::reset_model(bool asserted)
{
  (mkMergeSort_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkMergeSort::get_instance()
{
  return mkMergeSort_instance;
}

/* Fill in version numbers */
void MODEL_mkMergeSort::get_version(unsigned int *year,
				    unsigned int *month,
				    char const **annotation,
				    char const **build)
{
  *year = 2017u;
  *month = 7u;
  *annotation = "A";
  *build = "1da80f1";
}

/* Get the model creation time */
time_t MODEL_mkMergeSort::get_creation_time()
{
  
  /* Fri Nov  9 05:43:47 UTC 2018 */
  return 1541742227llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkMergeSort::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkMergeSort::dump_state()
{
  (mkMergeSort_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkMergeSort & mkMergeSort_backing(tSimStateHdl simHdl)
{
  static MOD_mkMergeSort *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkMergeSort(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkMergeSort::dump_VCD_defs()
{
  (mkMergeSort_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkMergeSort::dump_VCD(tVCDDumpType dt)
{
  (mkMergeSort_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkMergeSort_backing(sim_hdl));
}
